### ISSUE TITLE
Fatal Error pushing Java 11 app

### ISSUE THREAD

**Issue by timoteosoutello** [cloudfoundry/java-buildpack#711]
Hello,

I upgraded an app from Java JDK 8 to Java JDK11 using SpringBoot. 
I also put on manifest the parameter JBP_CONFIG_OPEN_JDK_JRE = { jre: { version: 11.+}}  

But when tried to push, a fatal error was trowed:
PS: I didn't specified a buildpack. 

> JVM Memory Configuration: -Xmx7675002K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=201605K
> [APP/PROC/WEB/0] [OUT] -Djava.ext.dirs=/home/vcap/app/.java-buildpack/container_security_provider:/home/vcap/app/.java-buildpack/open_jdk_jre/lib/ext is not supported. Use -classpath instead.
> [APP/PROC/WEB/0] [ERR] Error: Could not create the Java Virtual Machine.
> [APP/PROC/WEB/0] [ERR] Error: A fatal exception has occurred. Program will exit

The only way to pass this issue was to overwrite the java.ext.dirs to null

I want to know if this is the correct solution and what other possibilities over here.
When I push a new app using Java 11 this doesn't happen and this parameter is not filled.

Not sure if is a problem with cache on the buildpack that doest not update when the app is migrated.

Based on that article
https://docs.oracle.com/javase/10/migrate/toc.htm#JSMIG-GUID-8E83E51A-88A3-4E9A-8E2A-66E1D66A966C, shouldn't the buildpack update with the corresponding correct value ?

Thanks !

**Comment by nebhale** [comment]
The issue you're running into was [fixed in 4.17](https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.17).

**Comment by Maghil** [comment]
I'm facing the issue still for one space while the other space passed, cache problem?
